### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by Sc00bz** [mbroz/PHCtest#1]
First off, some of the submissions aren't memory hard at their "minimum" t_cost. Also you should graph time vs memory. The graph of time vs m_cost is mostly worthless.

To be fairer you probably want to match the number of times the memory is looped through "round". The best way would be to match how resistant the algorithm is to TMTO with a given t_cost, but I have not done this yet. So this is as good as we have right now. Since we can't find settings where they all do the same number of rounds we need to do different runs:

| Name | t_cost for 2x | t_cost for 3x | t_cost for 4x | t_cost for 5x |
| --- | --- | --- | --- | --- |
| Argon | 2 | 3 | 4 | 5 |
| battcrypt | 0 | 1 | 2* | - |
| Catena | 2 | 3 | 4 | 5 |
| Lyra2 | 2 | 3 | 4 | 5 |
| POMELO | 1 | - | 2 | - |
| Pufferfish | - | 0 | - | 1 |
| yescrypt | 3 | 4 | 5 | 6 |

\* Correct value, on the PHC list I had a typo.

Luckily we can mostly match m_costs:

| Name | m_cost for X KiB |
| --- | --- |
| Argon | X |
| battcrypt | log2(X) - 3 |
| Catena | log2(X) + 4 |
| Lyra2 | X / 24 |
| POMELO | log2(X) - 3 |
| Pufferfish | log2(X) |
| yescrypt | log2(X) |

| Name | 128 KiB | 256 KiB | 512 KiB | 1 MiB | 2 MiB | 4 MiB | 8 MiB |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Argon | 128 | 256 | 512 | 1,024 | 2,048 | 4,096 | 8,192 |
| battcrypt | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| Catena | 11 | 12 | 13 | 14 | 15 | 16 | 17 |
| Lyra2* | 5* | 11 | 21* | 43 | 85* | 171 | 341* |
| POMELO | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| Pufferfish | 7 | 8 | 9 | 10 | 11 | 12 | 13 |
| yescrypt** | 4 | 5 | 6 | 7 | 8 | 9 | 10 |

| Name | 16 MiB | 32 MiB | 64 MiB | 128 MiB | 256 MiB | 512 MiB |
| --- | --- | --- | --- | --- | --- | --- |
| Argon | 16,384 | 32,768 | 65,536 | 131,072 | 262,144 | 524,288 |
| battcrypt | 11 | 12 | 13 | 14 | 15 | 16 |
| Catena | 18 | 19 | 20 | 21 | 22 | 23 |
| Lyra2* | 683 | 1,365* | 2,731 | 5,461* | 10,923 | 21,845* |
| POMELO | 11 | 12 | 13 | 14 | 15 | 16 |
| Pufferfish | 14 | 15 | 16 | 17 | 18 | 19 |
| yescrypt** | 11 | 12 | 13 | 14 | 15 | 16 |

| Name | 1 GiB | 2 GiB | 4 GiB | 8 GiB |
| --- | --- | --- | --- | --- |
| Argon | 1,048,576 | 2,097,152 | 4,194,304 | 8,388,608 |
| battcrypt | 17 | 18 | 19 | 20 |
| Catena | 24 | 25 | 26 | 27 |
| Lyra2* | 43,691 | 87,381* | 174,763 | 349,525* |
| POMELO | 17 | 18 | 19 | 20 |
| Pufferfish | 20 | 21 | 22 | 23 |
| yescrypt** | 17 | 18 | 19 | 20 |

\* All Lyra2 numbers are rounded up or down by 8 KiB. Numbers marked with \* are
rounded down 8 KiB.
*\* All yescrypt numbers are rounded down by 11 KiB.

This is basically what I said in my email to the PHC list http://article.gmane.org/gmane.comp.security.phc/2550

**Comment by mbroz** [comment]
Hi Steve,
I tried to regenerate data (added Argon2) and added some charts (memory/time):
with min t_cost:
https://github.com/mbroz/PHCtest/blob/master/output/round2_Lenovo_X230_i5_16G/m_cost/memory_time.png

with your table above, up to 1GiB, all 2/3/4/5 rounds in one:
https://github.com/mbroz/PHCtest/blob/master/output/round2_Lenovo_X230_i5_16G/mc_cost_2/memory_time_round.png

Seems that Catena-Butterfly need different calculation for memory.

**Comment by Sc00bz** [comment]
OMG "2/3/4/5 rounds in one" is awesome.

I noticed battcrypt is in the 5x chart although there isn't a t_cost that does 5x and POMELO is in 3x and 5x although there isn't a t_cost for those. It seems like those were run with a lower setting.

Also "real memory use" is that measured at run time?

**Comment by mbroz** [comment]
Battcrypt/POMELO is there only in key legend (so we have the same color per series for all 4 charts), its input is empty if not defined in yout table (no points on graph). I should probably make it with different font (strikeout or so).

Real memory us is simple difference of getrusage(RUSAGE_SELF, ...) before and after run (well, here maximum of three runs).

So for small memory allocations it can be even zero (because that process already have some memory pre-allocated). My intention was to show that it really have expected peak there. (So it will not match your calculation exactly but it must be very close.)

**Comment by Sc00bz** [comment]
I pick them because their symbols are on the chart. This problem means that they are for a different algo.

Ahh...
Lyra2-SSE and POMELO-SSE on 3x and 5x are the same.
Argon2i-SSE and battcrypt on 5x are the same.

**Comment by Sc00bz** [comment]
Ohhh I get it now :)

**Comment by mbroz** [comment]
Seems I automatic coloring mixed up it somehow, I added explicit colors, so it should match table now, please check it...

**Comment by Sc00bz** [comment]
Cool looks correct. Hmm, did you run yescrypt at 2GiB on the 3x chart? I'm asking because on the other 3 charts yescrypt lines up with all the others at 1 GiB. Well besides Catena-Butterfly.

**Comment by mbroz** [comment]
Yes, I mentioned it in list - there is a typo in script, so yescrypt was tested for 2Gib there. I will rerun it for all algs overnight probably.
